# Generated by Django 5.0.2 on 2025-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=100)),
                ('patientage', models.IntegerField()),
                ('patientgender', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctorname', models.CharField(max_length=100)),
            ],
        ),
    ]
