# Generated by Django 5.0.2 on 2025-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/')),
                ('detailshtml', models.CharField(max_length=100)),
            ],
        ),
    ]
